spring:
  application:
    name: schola-backbone-server
  datasource:
    url: jdbc:mariadb://mariadb:3306/db
    username: root
    password: root
  data:
    redis:
      host: redis
      port: 6379
      password: root
      repositories:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: admin
